apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: simple-blog-api
          image: sonam889/simple_blog_api
          ports:
            - containerPort: 3000
          env: 
            - name: POSTGRES_HOST
              value: postgres-simpleblog-cluster-ip-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_DB
              value: simple-blog-api
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKey      Ref:
                   key: POSTGRES_PASSWORD
                   name: pgpassword
          resources:
               limits: 
                 memory: "128Mi"
                 cpu: "500m"