apiVersion: networking.k8s.io/v1
kind: Ingres
metadata:
  name: ingres-service
  annotations: 
     kubernetes.io/ingres.class: nginx
     nginx.ingres.kubernetes.io/use-regx: "true"
     nginx.ingres.kubernetes.io/rewrite-target: /$1
spec:
  rules:
     - http:
        paths:
           - path: /?(.*)
             pathtype: Prefix
             backend: 
                service: 
                   name: api-simpleblog-cluster-ip-service
                   port: 
                     number: 3000

